### PR TITLE
Support and moveit files for Yaskawa CSDA10F

### PR DESCRIPTION
**Pull request by amrith1007**

### CODE REVIEW

**Comment by amrith1007** [comment]
@shaun-edwards @gavanderhoorn can you guys help me out here. I am trying to make a pull request for the support and move it files for the Yaskawa CSDA10F. However, the Travis CI builder fails for the kinetic distro and passes for the indigo distro. I have no problem running path planning in both indigo and kinetic (I have check them in both versions).

**Comment by shaun-edwards** [comment]
@amrith1007, the roslaunch check fails with this error:
```
<testsuite errors="0" failures="1" name="roslaunch-check_test_launch_test.xml.xml" tests="1" time="1"><testcase classname="roslaunch.RoslaunchCheck" name="motoman_csda10f_support_test_launch_test_xml" status="run" time="1"><failure message="roslaunch check [/root/catkin_ws/src/motoman_experimental/motoman_csda10f_support/test/launch_test.xml] failed" type="" /></testcase><system-out>&lt;![CDATA[
[/root/catkin_ws/src/motoman_experimental/motoman_csda10f_support/test/launch_test.xml]:
	while processing /root/catkin_ws/src/motoman_experimental/motoman_csda10f_support/launch/load_csda10f.launch:
Invalid &lt;param&gt; tag: Cannot load command parameter [robot_description]: command [/opt/ros/kinetic/share/xacro/xacro.py '/root/catkin_ws/src/motoman_experimental/motoman_csda10f_support/urdf/csda10f.xacro'] returned with code [2]. 
Param xml is &lt;param command="$(find xacro)/xacro.py '$(find motoman_csda10f_support)/urdf/csda10f.xacro'" name="robot_description"/&gt;
]]&gt;</system-out></testsuite>
-------------------------------------------------
build/motoman_csda10f_support/test_results/motoman_csda10f_support/roslaunch-check_test_launch_test.xml.xml: 1 tests, 0 errors, 1 failures, 0 skipped
```

I'm not sure why this fails in kinetic only.  Does anything in this error message catch your eye?

**Comment by Danfoa** [comment]
@shaun-edwards @amrith1007 I have corrected little details on the .xacro files, clean up some files that weren't used and added some comments.

The CSDA10F packages (support and Moveit configuration) are only being pushed to the Kinetic-Devel...that is why Indigo-devel was passing Travis CI test, but in theory I don't see a reason why it wouldn't work on Indigo once push to this branch.

**Comment by Danfoa** [comment]
Good day @shaun-edwards @gavanderhoorn, this is just a friendly reminder for the pull request, we are using this files for [the integration of the CSDA10F ](https://github.com/Danfoa/invite-robotics) robot for a German Company and would like to have the experts opinion on it. As a matter of fact I know that @amrith1007 change the tool_0 link position, can you please push that change my friend.

Thanks to all, sorry to bother.

**Comment by amrith1007** [comment]
As of now, the URDF and the moveit files for the CSDA10F have been tested on the kinetic-devel. Awaiting confirmation or comments from the experts :) Thanks in advance.

**Comment by amrith1007** [comment]
As of now, the URDF and the moveit files for the CSDA10F have been tested on the kinetic-devel. Awaiting confirmation or comments from the experts :) Thanks in advance.

**Comment by shaun-edwards** [comment]
@amrith1007, sorry for our delay in getting back to you.  I took a quick look.  I'm not familiar with all the details of dual arm setups, so I wouldn't consider myself an "expert".

The only "issue" I notices was that you chose a different naming convention for joint from our other robots.  See [bmda3](https://github.com/ros-industrial/motoman_experimental/blob/kinetic-devel/motoman_bmda3_support/config/joint_names_bmda3.yaml).  Did you have a particular reason for doing this?

**Comment by Danfoa** [comment]
Hi @shaun-edwards, I believe @amrith1007 based the joint naming convention following the already accepted [motoman_sda10f_support/config/joint_names_sda10f.yaml](https://github.com/ros-industrial/motoman/blob/kinetic-devel/motoman_sda10f_support/config/joint_names_sda10f.yaml), since both robots are quite similar.

**Comment by shaun-edwards** [comment]
@Danfoa, thanks for the pointer.  Thanks for the contribution....accepting.  As this is a the "experimental" we will let this mature in this repo for a bit.  However, if you should want to push this into the main motoman repo, please let me know.

**Comment by Danfoa** [comment]
@shaun-edwards thank you very much,

We will be testing the packages with the real robot soon, when we confirm everything is ok i will push again here and probably in the non experimental repo too.

**Comment by amrith1007** [comment]
@shaun-edwards  thank you very much for the merge. As Daniel said, I stuck to the same naming convention as the SDA10F (thanks for clearing that up @Danfoa ). As you said we could push it onto the main motoman repo when the testing with the real robot is done. Cheers guys !

**Pull request merged**
