### PR TITLE
Initial commit for ES165RD-II support

### PR DESCRIPTION
**Pull request by marip8**

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Nice work.

If I may make some suggestions:

 1. rename the package to `motoman_es_support`: not entirely sure, but looking at the product lines there appears to be an `ES` robot series, in which the `ES165xx` is a particular variant (together with the `200`, the `280` and others). Support pkgs are intended to support multiple variants, to cut down on the nr of packages that we'd have to create otherwise.
 1. use 2 spaces for indentation everywhere (xacros, launch and xml files)
 1. make `use_gui` a private param of `joint_state_publisher` (in the `test_..launch` file)
 1. be specific about which variant is supported in the package manifest: right now it says "the base model"
 1. don't use shorted links in the manifest: retention isn't great, making the actual document harder to find if it is ever moved (on yaskawa's servers)
 1. I don't believe `motoman_driver` is a *downloading* driver (I see a `robot_interface_download_es165rdii.launch` file. Did you copy this from an ABB package?)
 1. `material` names do not get a `${prefix}`
 1. ideally, `joint` transforms translate in a single dimension only (ie: `x` or `z`)
 1. the `${radians(..)}` is nice, why the inconsistencies? There is a `velocity` limit there which does the conversion 'manually'.
 1. adding the `base` frame is nice, thanks for that. I'm not sure however about where you put the origin of that frame in your xacro. Have you verified this?

**Comment by shaun-edwards** [comment]
I updated the branch to kinetic...please let me know if it's needed in an early branch.

**Comment by gavanderhoorn** [comment]
Personally I would like to see all of these pkgs (including the `mpl80` from #13) to be included in `indigo-devel` as  well.

**Comment by gavanderhoorn** [comment]
Travis is failing because this repository has it enabled, but not configured.

I've opened #15 to rectify this.

After that is merged, could you rebase this PR @marip8?

**Comment by marip8** [comment]
@gavanderhoorn I believe the latest commit addresses your comments in 1, 2, 3, 4, 7, 8, and 9.

Regarding 5, the URL to the datasheet has ampersands, so the package failed to build when I included it. Can you advise on how to get around that issue?

Regarding 6, I did copy that launch file from an ABB package; should I rename it to something more appropriate or do something else with it?

Regarding 10, I'm not sure what Motoman considers its world coordinate frame to be relative to the base_link; I'll look into fixing that

**Comment by marip8** [comment]
@gavanderhoorn I can do the rebase when that change is made

**Comment by gavanderhoorn** [comment]
@marip8 wrote:
> Regarding 5, the URL to the datasheet has ampersands, so the package failed to build when I included it. Can you advise on how to get around that issue?

You could perhaps replace them with `&amp;`.

> Regarding 6, I did copy that launch file from an ABB package; should I rename it to something more appropriate or do something else with it?

Take a look at the other support pkgs in `motoman` ([motoman_sia20d_support](https://github.com/ros-industrial/motoman/tree/jade-devel/motoman_sia20d_support/launch) fi): you'll see they have `robot_interface_streaming_*.launch` files. The MotoROS driver is a *streaming* driver, so the launch file should reflect that.

> Regarding 10, I'm not sure what Motoman considers its world coordinate frame to be relative to the base_link; I'll look into fixing that

I think https://github.com/ros-industrial/motoman/pull/167#issuecomment-292966787 by @EricMarcil could help here:

> The Motoman standard is that the robot coordinate system is at the S-axis rotation axis but at the height of the L-axis (2nd axis) rotation center.

Making the `base` frame correspond to that should make us conform to what Motoman does.

**Comment by gavanderhoorn** [comment]
See [motoman_mpl_support/urdf/mpl80_macro.xacro](https://github.com/ros-industrial/motoman_experimental/blob/13d3f24abfcf9591e591d150b895bd7567eb3648/motoman_mpl_support/urdf/mpl80_macro.xacro#L172-L178) for an example which I think you could duplicate.

**Comment by gavanderhoorn** [comment]
@marip8: could you rebase on `kinetic-devel`? The Travis config was just merged in #15 and I'd like to see this PR tested as well.

**Comment by marip8** [comment]
@shaun-edwards

**Comment by shaun-edwards** [comment]
@marip8, is there a reason you changed me to maintainer?  I am the maintainer for motoman but you could also be a maintainer (especially for packages with which you are more familiar).  Just thought I'd ask.

**Comment by marip8** [comment]
@shaun-edwards I'm fine with being the maintainer for this package. I was initially under the impression that the maintainer tag was for the repo manager, so that's why I had you there

**Comment by shaun-edwards** [comment]
@marip8, being a maintainer is a commitment...are you up for it?  We can discuss tomorrow.  I'll be in the office in the morning.

**Comment by shaun-edwards** [comment]
@marip8, travis is failing here: https://travis-ci.org/ros-industrial/motoman_experimental/jobs/233467864#L708

Let me know if you need help doing this tomorrow.

**Comment by gavanderhoorn** [comment]
Continued in #49.

**Pull request closed without merging**
