### PR TITLE
Integrate Travis using industrial_ci.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

This is the default ros-i `.travis.yml` copied to this repository.

### CODE REVIEW

**Comment by shaun-edwards** [comment]
Should we create an indigo branch for this?

**Comment by gavanderhoorn** [comment]
Not necessarily I think. As long as the packages build on an Indigo installation, it doesn't really matter what branch they are in.

**Comment by gavanderhoorn** [comment]
I'm checking why the travis build failed.

**Comment by gavanderhoorn** [comment]
Looks like `motoman_robot_pkg_gen` has `industrial_robot_pkg_gen` listed as a `build_depend` (and searched for [here](https://github.com/ros-industrial/motoman_experimental/blob/791d4160f30386924cdf382984986a6d744cd0cd/motoman_robot_pkg_gen/CMakeLists.txt#L5)):

```
[motoman_robot_pkg_gen] CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package): 
[motoman_robot_pkg_gen]   Could not find a package configuration file provided by 
[motoman_robot_pkg_gen]   "industrial_robot_pkg_gen" with any of the following names: 
[motoman_robot_pkg_gen]     industrial_robot_pkg_genConfig.cmake 
[motoman_robot_pkg_gen]     industrial_robot_pkg_gen-config.cmake 
[motoman_robot_pkg_gen]  
[motoman_robot_pkg_gen]   Add the installation prefix of "industrial_robot_pkg_gen" to 
[motoman_robot_pkg_gen]   CMAKE_PREFIX_PATH or set "industrial_robot_pkg_gen_DIR" to a directory 
[motoman_robot_pkg_gen]   containing one of the above files.  If "industrial_robot_pkg_gen" provides 
[motoman_robot_pkg_gen]   a separate development package or SDK, be sure it has been installed. 
[motoman_robot_pkg_gen] Call Stack (most recent call first): 
[motoman_robot_pkg_gen]   CMakeLists.txt:4 (find_package)
```

causing it to fail.

That dependency should be removed: `build_depend`s are rarely needed for Python packages. Afaict, certainly not in this case.

**Comment by gavanderhoorn** [comment]
Travis integration is already paying off :)

**Comment by shaun-edwards** [comment]
> As long as the packages build on an Indigo installation, it doesn't really matter what branch they are in

Doesn't it matter if we want to catch version specific failures?  Is there a reason not to create an `indigo-devel` branch or configure travis for `hydro`?

**Comment by gavanderhoorn** [comment]
> Doesn't it matter if we want to catch version specific failures?

Well, yes. But only if there is going to be development for multiple versions, which I don't think will happen with this repository (seeing as Hydro is EOL).

> Is there a reason not to create an `indigo-devel` branch 

Don't think so.

> or configure travis for `hydro`?

That is a bit harder. Afaik the ros-i ci infrastructure has been set up for Trusty/Indigo specifically.

**Comment by gavanderhoorn** [comment]
I can think of one reason actually: there are some open PRs against `hydro-devel`, and those will have to be resubmitted. Might be nice to accept (or close them) and only then branch to Indigo.

**Comment by shaun-edwards** [comment]
+1, but I think this version inconsistency is something to address in the future.  For now, this is better than nothing.

**Comment by shaun-edwards** [comment]
Let me know when this is ready to merge/if you plan to fix the travis issue

**Comment by gavanderhoorn** [comment]
Let's not merge this one, but cleanup / merge outstanding PRs for `hydro-devel` first. Then I'll re-submit this PR against `indigo-devel`.

**Comment by gavanderhoorn** [comment]
#7 should be easy (readme update). #8 needs some more work. Is #6 going to be merged, or are we keeping that around as a backup?

**Pull request closed without merging**
