### PR TITLE
MH12 Support Package

### PR DESCRIPTION
**Pull request by Jmeyer1292**
* Not sure if this belongs in the generic mh_support package
* Joint limits are probably wrong (spec sheet reference is different).
* Axis directions (3-6) are probably wrong

Collision models are just convex hulls of the visual models.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@Jmeyer1292 wrote:
>  - Not sure if this belongs in the generic mh_support package

If this is an MH variant, it should probably be added to that package, yes.

**Comment by Jmeyer1292** [comment]
Maybe, but other motoman robots (e.g. the MH5) haven't followed that convention and if you look at Yaskawa's website they have 20+ current robots of all shapes and sizes that fall under the MH brand of robots.

None of that means it's not a good idea to start now.

**Comment by shaun-edwards** [comment]
I think we should start adding to the MH package.

**Comment by gavanderhoorn** [comment]
@Jmeyer1292 wrote:
> Maybe, but other motoman robots (e.g. the MH5) haven't followed that convention

yes, those were added before ros-industrial/motoman#65 was discussed. There was/is no real conclusion, but the current approach -- please correct me @shaun-edwards -- is to create support packages for the series that Yaskawa defines. In this case that would seem to be the `mh` series.

Most (all?) support pkgs (in `motoman`) that don't follow this convention have been deprecated for quite some time now, and should actually be removed or merged into proper series support packages.

> and if you look at Yaskawa's website they have 20+ current robots of all shapes and sizes that fall under the MH brand of robots.

This is not a done deal, and I agree that what I described above can result in rather large support packages, so I'd appreciate any input you may have.

Ideally we group models according to criteria that the mfg uses, to facilitate users that know the mfgs naming scheme. But we should always keep an eye on things like total nr of pkgs, size of pkgs, etc.

That is the reason we have support pkgs in the first place, and don't just create a description pkg for every variant.

**Comment by gavanderhoorn** [comment]
Closing as we have MH-12 support in the main repository.

**Pull request closed without merging**
