### PR TITLE
Basic support for Yaskawa Motoman GP180-120 6DOF arm

### PR DESCRIPTION
**Pull request by jmarsik**
Meshes are derived from official Yaskawa 3D model files.

I didn't know if I should commit this to motoman_experimental or motoman repository ... is this the right one?

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks for the PR.

> I didn't know if I should commit this to motoman_experimental or motoman repository ... is this the right one?

You may submit to `ros-industrial/motoman` directly. If @EricMarcil and/or @ted-miller review the submission I'm confident it is OK.

Unfortunately I cannot transfer PRs, so if/when you re-open there, I'll add some comments on specific aspects of the PR.

**Comment by EricMarcil** [comment]
@gavanderhoorn: I will try to review it tomorrow and then if all is good we can put in the Motoman branch.

**Comment by gavanderhoorn** [comment]
I'd prefer it if @jmarsik could submit to `ros-industrial/motoman` first and then ask you to do the review.

**Comment by jmarsik** [comment]
I will do that and post link to the new PR here. Probably tomorrow.

**Comment by jmarsik** [comment]
New pull request to motoman repository created, check it here https://github.com/ros-industrial/motoman/pull/277

The Travis build is still failing here, just for ROS Indigo, there is something wrong with using properties in xacro file (property DEG2RAD). It works fine in ROS Kinetic.

**Pull request closed without merging**
