### PR TITLE
Initial commit for EPX support

### PR DESCRIPTION
**Pull request by marip8**

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@marip8, can you provide a screenshot or the URDF?

**Comment by gavanderhoorn** [comment]
I don't think @shaun-edwards meant for the screenshot to be added to the repository @marip8 ;)

**Comment by marip8** [comment]
motoman_epx1250

My bad; I was unclear what the screenshot was wanted for.

**Comment by shaun-edwards** [comment]
+1...thanks for the contribution.

**Pull request merged**
